version: "3.7"
services:
  # ====================================================================================================================
  # POSTGRES SERVER
  # ====================================================================================================================
  postgres-docker:
    image: postgres:14-alpine
    container_name: confectioner-dev-postgresql
    environment:
      POSTGRES_DB: confectioner-db
      POSTGRES_PASSWORD: 123456

    ports:
      - "5433:5432"
    volumes:
      - ./.data/postgresql/data:/var/lib/postgresql/data
    networks:
      - dev-network
# ======================================================================================================================
# NETWORK
# ======================================================================================================================
networks:
  dev-network:
    driver: bridge